version: "3"
services:
  builder:
    image: so2-tp3-builder
    container_name: so2-tp3-builder
    build: .
  nginx:
    image: nginx:latest
    container_name: so2-tp3-nginx
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy_net
    links:
      - so2-tp3-stats
      - so2-tp3-users
    ports:
      - 80:80
      - 443:443
  so2-tp3-stats:
    image: so2-tp3-stats
    container_name: so2-tp3-stats
    build: src/stats
    networks:
      - proxy_net
    ports:
    - 8080:8080
    expose:
      - 8080
  so2-tp3-users:
    image: so2-tp3-users
    container_name: so2-tp3-users
    build: src/users
    networks:
      - proxy_net
    ports:
    - 7788:7788
    expose:
      - 7788
networks:
  proxy_net:
    driver: bridge