version: "3"
services:
  eam_so2_tp3_builder:
    image: eam_so2_tp3_builder
    container_name: eam_so2_tp3_builder
    build: .
  eam_so2_tp3_nginx:
    image: nginx:latest
    container_name: eam_so2_tp3_nginx
    restart: always
    depends_on:
      - eam_so2_tp3_stats
      - eam_so2_tp3_users
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    links:
      - eam_so2_tp3_stats
      - eam_so2_tp3_users
    ports:
      - 80:80
      - 443:443
  eam_so2_tp3_stats:
    image: eam_so2_tp3_stats
    container_name: eam_so2_tp3_stats
    restart: always
    build: src/stats
    expose:
      - "8080"
    ports:
      - 8080:8080
  eam_so2_tp3_users:
    image: eam_so2_tp3_users
    container_name: eam_so2_tp3_users
    restart: always
    build: src/users
    expose:
      - "7788"
    ports:
      - 7788:7788