version: "3"
services:
  builder:
    image: so2-tp3-builder
    container_name: so2-tp3-builder
    build: .
  nginx:
    image: nginx:latest
    container_name: so2-tp3-nginx
    depends_on:
      - stats
      - users
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy_net
    links:
      - stats
      - users
    ports:
      - 80:80
      - 443:443
  stats:
    image: so2-tp3-stats
    container_name: so2-tp3-stats
    build: src/stats
    networks:
      - proxy_net
    ports:
    - 8080:8080
  users:
    image: so2-tp3-users
    container_name: so2-tp3-users
    build: src/users
    networks:
      - proxy_net
    ports:
    - 7788:7788
networks:
  proxy_net:
    driver: bridge